//Generated by Flan. http://2bam.com/flan
//From: test1.flan

package  {
	import flash.geom.*;

	
	public class Test {
		public var info:Object;

		function Test() {
			info = {
				name:"Test",
				bounds:new Rectangle(0,0,641,481),
				bgColor:0xff000000,
				custom:null,
				layers:[		//add in order
					{	//LAYER Main
						name:"Main",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Main,
						tileMap: {
							image:_Img_bgtiles_b8e1fc0d,
							firstCollide:3,
							firstDraw:0,
							CSV: _CSV_Main
						}
					},

				]
			};
		}
//----------IMAGES----------
		[Embed(source='../TILES/bgtiles.png')] public var _Img_bgtiles_b8e1fc0d:Class;

		
//----------SPRITES----------
		public var _Sprites_Main:Array = [
		];



//----------CSV----------
		public var _CSV_Main:String = 
			"3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,3\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,1,1,2,2,2,2,1,1,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,1,1,2,2,2,2,1,1,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,2,2,2,2,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3\n";



	}
}