//Generated by Flan. http://2bam.com/flan
//From: ../../flan_test_folder/levelSelect.flan

package  {
	import flash.geom.*;

	
	public class LevelSelect {
		public var info:Object;

		function LevelSelect() {
			info = {
				name:"LevelSelect",
				bounds:new Rectangle(0,0,641,481),
				bgColor:0xff000000,
				custom:null,
				layers:[		//add in order
					{	//LAYER LevelIcon
						name:"LevelIcon",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_LevelIcon,
						tileMap: {
							image:_Img_bgtiles_cfc289d7,
							firstCollide:1,
							firstDraw:1,
							CSV: _CSV_LevelIcon
						}
					},
					{	//LAYER Finish
						name:"Finish",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Finish,
						tileMap: {
							image:_Img_finish_29e1666a,
							firstCollide:1,
							firstDraw:1,
							CSV: _CSV_Finish
						}
					},
					{	//LAYER Player
						name:"Player",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Player,
						tileMap: {
							image:_Img_bgtiles_cfc289d7,
							firstCollide:1,
							firstDraw:1,
							CSV: _CSV_Player
						}
					},
					{	//LAYER Enemy
						name:"Enemy",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Enemy,
						tileMap: {
							image:_Img_bgtiles_cfc289d7,
							firstCollide:1,
							firstDraw:1,
							CSV: _CSV_Enemy
						}
					},
					{	//LAYER Coin
						name:"Coin",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Coin,
						tileMap: {
							image:_Img_bgtiles_cfc289d7,
							firstCollide:1,
							firstDraw:1,
							CSV: _CSV_Coin
						}
					},
					{	//LAYER Main
						name:"Main",
						position:new Point(0,0),
						scrollFactor:new Point(1,1),
						sprites: _Sprites_Main,
						tileMap: {
							image:_Img_bgtiles_cfc289d7,
							firstCollide:3,
							firstDraw:0,
							CSV: _CSV_Main
						}
					},

				]
			};
		}
//----------IMAGES----------
		[Embed(source='img/level/bgtiles.png')] public var _Img_bgtiles_cfc289d7:Class;
		[Embed(source='img/level/finish.png')] public var _Img_finish_29e1666a:Class;

		
//----------SPRITES----------
		public var _Sprites_LevelIcon:Array = [
			{x:43,y:44,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:140,y:43,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:248,y:47,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:367,y:49,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:491,y:51,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:42,y:158,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:142,y:162,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:241,y:161,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:370,y:164,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:481,y:163,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:44,y:264,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:148,y:264,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:246,y:262,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:369,y:256,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:490,y:260,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:49,y:366,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:150,y:363,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:251,y:361,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:374,y:361,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
			{x:494,y:361,id:"LevelIcon",cls:LevelIcon,custom:{value:""},typeImg:null, typeParams:null},
		];

		public var _Sprites_Finish:Array = [
		];

		public var _Sprites_Player:Array = [
		];

		public var _Sprites_Enemy:Array = [
		];

		public var _Sprites_Coin:Array = [
		];

		public var _Sprites_Main:Array = [
		];



//----------CSV----------
		public var _CSV_LevelIcon:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";
		public var _CSV_Finish:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";
		public var _CSV_Player:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";
		public var _CSV_Enemy:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";
		public var _CSV_Coin:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";
		public var _CSV_Main:String = 
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n"+
			"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\n";



	}
}